### ISSUE TITLE
can't install via npm on windows

### ISSUE THREAD

**Issue by Partysun** [atom/node-chromium-pickle#3]
![2015-07-30 09 39 20](https://cloud.githubusercontent.com/assets/522287/8975953/13bd6f12-369f-11e5-897a-f9450415629c.png)

**Comment by paulcbetts** [comment]
Install VS2013 Update 4 then `set GYP_MSVS_VERSION=2013`

**Comment by Partysun** [comment]
Oh Yeah!) Thank you.
